// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapstormshield = map[string]*DeviceData{
    "Stormshield SN2000": {
        Manufacturer: "Stormshield",
        Model: "Stormshield SN2000",
        Slug: "stormshield-sn2000",
        UHeight: 1,
        PartNumber: "sn2000",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 8.6,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "Keyboard", Type: "other", Label: "", Poe: false },
            { Name: "Rear USB1", Type: "usb-a", Label: "", Poe: false },
            { Name: "Rear USB2", Type: "usb-a", Label: "", Poe: false },
            { Name: "Rear USB3", Type: "usb-a", Label: "", Poe: false },
            { Name: "Rear USB4", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PS1", Label: "", Position: "1" },
            { Name: "PS2", Label: "", Position: "2" },
            { Name: "FAN1", Label: "", Position: "1" },
            { Name: "FAN2", Label: "", Position: "2" },
            { Name: "FAN3", Label: "", Position: "3" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt1", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "mgmt2", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "port1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "Stormshield SN2200": {
        Manufacturer: "Stormshield",
        Model: "Stormshield SN2200",
        Slug: "stormshield-sn2200",
        UHeight: 1,
        PartNumber: "sn2200",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 9.93,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Console", Type: "rj-45", Label: "", Poe: false },
            { Name: "Keyboard", Type: "other", Label: "", Poe: false },
            { Name: "Front USB1", Type: "usb-a", Label: "", Poe: false },
            { Name: "Front USB2", Type: "usb-a", Label: "", Poe: false },
            { Name: "Front USB3", Type: "usb-c", Label: "", Poe: false },
            { Name: "Rear USB1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PS1", Label: "", Position: "1" },
            { Name: "PS2", Label: "", Position: "2" },
            { Name: "FAN1", Label: "", Position: "1" },
            { Name: "FAN2", Label: "", Position: "2" },
            { Name: "FAN3", Label: "", Position: "3" },
            { Name: "FAN4", Label: "", Position: "4" },
            { Name: "FAN5", Label: "", Position: "5" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "mgmt1", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "mgmt2", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "port1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port8", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
