// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapnvidia = map[string]*DeviceData{
    "Jetson Xavier NX Developer Kit": {
        Manufacturer: "Nvidia",
        Model: "Jetson Xavier NX Developer Kit",
        Slug: "nvidia-jetson-xavier-nx-developer-kit",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "HDMI", Type: "other", Label: "", Poe: false },
            { Name: "Display Port", Type: "other", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "dc-terminal", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "SN2201": {
        Manufacturer: "Nvidia",
        Model: "SN2201",
        Slug: "nvidia-sn2201",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: true,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 7.41,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "con0", Type: "usb-mini-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp6", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp7", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp8", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp9", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp10", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp11", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp12", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp13", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp14", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp15", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp16", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp17", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp18", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp19", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp20", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp21", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp22", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp23", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp24", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp25", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp26", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp27", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp28", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp29", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp30", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp31", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp32", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp33", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp34", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp35", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp36", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp37", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp38", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp39", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp40", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp41", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp42", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp43", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp44", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp45", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp46", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp47", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp48", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "swp49", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp50", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp51", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
            { Name: "swp52", Label: "", Type: "100gbase-x-qsfp28", MgmtOnly: false },
        },
    },
}
