// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapitk = map[string]*DeviceData{
    "CO05-1PC": {
        Manufacturer: "ITK",
        Model: "CO05-1PC",
        Slug: "itk-co05-1pc",
        UHeight: 1,
        PartNumber: "CO05-1PC",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 0.38,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
