// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapruggedcom = map[string]*DeviceData{
    "Rugged Switch RS900": {
        Manufacturer: "RuggedCOM",
        Model: "Rugged Switch RS900",
        Slug: "ruggedcom-rugged-switch-rs900",
        UHeight: 0,
        PartNumber: "RS900",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1.23,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "Serial", Type: "de-9", Label: "RS232", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC Input", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "1", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "2", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "3", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "4", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "5", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "6", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "7", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "8", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "9", Label: "", Type: "100base-fx", MgmtOnly: false },
        },
    },
}
