// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapsecuritycode = map[string]*DeviceData{
    "IPC-R50": {
        Manufacturer: "SecurityCode",
        Model: "IPC-R50",
        Slug: "securitycode-ipc-r50",
        UHeight: 1,
        PartNumber: "ipc-r50",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "CONSOLE", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU 12v 3a", Label: "", Type: "dc-terminal", MaximumDraw: 36, AllocatedDraw: 30 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port4", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port5", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "port1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
        },
    },
}
