// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapugreen = map[string]*DeviceData{
    "DXP4800Plus": {
        Manufacturer: "UGREEN",
        Model: "DXP4800Plus",
        Slug: "ugreen-dxp4800plus",
        UHeight: 4,
        PartNumber: "dxp4800plus",
        IsFullDepth: false,
        Airflow: "rear-to-front",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 3.79,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "dc-terminal", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN 1", Label: "LAN 1", Type: "10gbase-t", MgmtOnly: false },
            { Name: "LAN 2", Label: "LAN 2", Type: "2.5gbase-t", MgmtOnly: false },
        },
    },
}
