name: Generate Code and Commit

on:
  workflow_dispatch: # So we can run workflow manually
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  generate-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run go generate
        run: go generate ./...
        env:
          GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "No changes detected."
            exit 0
          else
            echo "Changes detected."
          fi

      - name: Commit changes
        if: success() && steps.check-for-changes.outcome == 'success'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          DATE=$(date '+%Y-%m-%d')
          git commit -m "fix(devicetype-library): updating data from remote repo <$DATE>."

      - name: Push changes
        if: success() && steps.check-for-changes.outcome == 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
